[package]
name = "urd"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
thiserror = "1.0"
regex = "1.0"
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[lib]
name = "urd"
path = "src/lib.rs"

[[bin]]
name = "urd"
path = "src/bin/urd.rs"