---
# Unified Daemon Configuration
# This file contains all configuration for the UR daemon

# Robot Configuration
robot:
  # Robot connection parameters
  host: "localhost"  # Change to robot IP in production
  ports:
    primary: 30001      # Primary client interface
    rtde: 30004         # Real-Time Data Exchange
    dashboard: 29999    # Dashboard server
  
  # Tool center point offset
  tcp_offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  
  # Movement parameters
  movement:
    speed: 0.1          # m/s
    acceleration: 0.1   # m/s²
    blend_radius: 0.01  # m
  
  # Connection settings
  connection:
    timeout: 10.0       # seconds
    retry_attempts: 3
    retry_delay: 2.0    # seconds

# Publishing Configuration
publishing:
  # Rate at which robot position is published/displayed (Hz)
  pub_rate_hz: 10
  
  # Number of decimal places for position/pose values in JSON output
  decimal_places: 4

# Command Configuration
command:
  # Monitor program execution via RTDE
  monitor_execution: true
  
  # Stream robot state output while processing commands
  # Options: false (disabled), true (continuous), "dynamic" (only on change)
  stream_robot_state: "dynamic"